format:
  html:
#    toc: true
#    toc-location: left
#    grid:
#      body-width: 1250px
    theme: theme.scss
  
link-external-newwindow: true

project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true

website:
  title: "Rbanism"
  navbar:
    logo: assets/icons/rbanism.png
    left:
      - about.qmd
      - resources.qmd
      - events.qmd
      - blog.qmd
      - contact.qmd
    right:
      - registration.qmd
  search: false
  page-footer:
    # NOTE - The specified justification is overriden in the CSS.
    left: |
      <span style="display: block;">
      ![](/assets/icons/rbanism.png){height=2em} 
      <span style="font-family: Montserrat; font-weight: 700">Rbanism</span>
      </span>
      <span style="display: block;">
      ![](/assets/icons/phone.png){height=24px}
      <span>+31 12 345 6789</span>
      </span>
      <span style="display: block;">
      ![](/assets/icons/email.png){height=24px} rbanism@tudelft.nl
      </span>
      <span style="display: block;">
      ![](/assets/icons/address.png){height=24px} Faculty of Architecture and the Built Environment \
      ![](/assets/imgs/pad.png){width=24px} Julianalaan 134, 2628 BL                                \
      ![](/assets/imgs/pad.png){width=24px} Delft, The Netherlands
      </span>
      <!--Social Media-->
      <span style="display: block;">
      <span style="font-family: Montserrat; font-weight: 700">Follow us</span>
      ![](/assets/third-party/logos/github.png){height=24px}
      ![](/assets/third-party/logos/linkedin.png){height=24px}
      ![](/assets/third-party/logos/twitter.png){height=24px}
      ![](/assets/third-party/logos/youtube.png){height=24px}
      </span>
      <!--Copyright-->
      <span style="display: block;">
      <span style="font-family: Montserrat">Copyright © 2023-2024 Rbanism</span>
      </span>
